# Generated by Django 3.1.7 on 2021-03-15 09:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', django_resized.forms.ResizedImageField(crop=None, default='profile/avatar.svg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 500], upload_to='profile/')),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('country', django_countries.fields.CountryField(default='IN', max_length=2)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(1997, 10, 19), null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile api',
                'verbose_name_plural': 'Profiles api',
            },
        ),
    ]
