# Generated by Django 3.1.7 on 2021-03-16 00:12

from django.db import migrations
import django_resized.forms
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[800, 800], upload_to=post.models.upload_location),
        ),
    ]
